### ISSUE TITLE
Does not work in CS2

### ISSUE THREAD

**Issue by BlogPlayCode** [zkxs/simple-crosshair-overlay#53]
It works properly when I launch CS in windowed mode but it does not appear when I launch CS in fullscreen (I play 4:3 that's important for me)

**Comment by zkxs** [comment]
simple-crosshair overlay only works on windowed or borderless-windowed mode games. This was an intentional design choice, as rendering into a fullscreen-exclusive game is not anti-cheat-compatible.

Other overlay applications that can render into fullscreen exclusive games work by hooking into the game process, and if the game has anticheat the overlay application must be whitelisted by the devs, as anticheat tends to dislike unknown processes hooking into the game it's trying to protect.
